### ISSUE TITLE
bitarray@2.3.7 failing to build

### ISSUE THREAD

**Issue by mmraz** [ilanschnell/bitarray#166]
We started having system wide deployment failures on impyla which has a transitive dependency on bitarray.  Versions 2.3.5 and 2.3.6 installed successfully.  Failure to build started with 2.3.7

Anaconda python 3.7
setuptools 60.9.3
pip 19.1.1

```
  Downloading https:/masked.host/artifactory/api/pypi/pypi-release/packages/packages/10/e6/cae15318a3074e38492b49989636802e3082dd1af4086259d54d9a382729/bitarray-2.3.7.tar.gz (89kB)
STDERR: ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/setuptools/dist.py", line 33, in <module>
        from ._importlib import metadata
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
        disable_importlib_metadata_finder(metadata)
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
        import importlib_metadata
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 466, in <module>
        __version__ = version(__name__)
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 433, in version
        return distribution(package).version
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 406, in distribution
        return Distribution.from_name(package)
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 175, in from_name
        dists = resolver(name)
      File "/opt/anaconda/2019.07/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
        found = self._search_paths(context.name, context.path)
    AttributeError: 'str' object has no attribute 'name'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-l5j3bwpj/bitarray/
```

**Comment by ilanschnell** [comment]
Thank you for using bitarray!  Hmm, I'm not sure what the problem is.  I tried `pip install bitarray` (on Linux x86_64, using Anaconda Python 3.7, and pip 21.2.2) and it worked fine.  I haven't done any changes regarding the `setup.py` install process in the bitarray 2.3.7 release.  In fact `setup.py` has not been touched in this release at all.

Your traceback seems unrelated to bitarray.  Could it be a problem with the setuptools version or some other configuration you are using?  Have you tried `pip install setuptools` (outside artifactory)?

**Comment by mmraz** [comment]
We just ended up adding a pin to bitarray@2.3.5 in our requirements file to override the unpinned transitive inclusion since that version installs as expected.  Just wanted to report the failure as a data point for the project.

**Comment by ilanschnell** [comment]
Thanks for reporting this issue, although it's unclear where the problem in bitarray is (or if it's a bitarray problem at all).

**Comment by mmraz** [comment]
I was able to reproduce the failure using an anaconda docker container.  Versions of setuptools >= 60.9.0 cause bitarray to fail to build. 

Using the following Dockerfile
```
FROM continuumio/anaconda3:2019.07 as conda
FROM ubuntu:16.04
RUN apt-get update && apt-get -q -y install gcc
COPY --from=conda /opt/conda /opt/conda
ENTRYPOINT /bin/bash
```

Running with the default version of setuptools which comes with the image allows a successful installation
```
$ docker run -it --rm conda
root@e6eab42d508c:/# /opt/conda/bin/pip install bitarray==2.3.7
Collecting bitarray==2.3.7
  Downloading https://files.pythonhosted.org/packages/10/e6/cae15318a3074e38492b49989636802e3082dd1af4086259d54d9a382729/bitarray-2.3.7.tar.gz (89kB)
     |████████████████████████████████| 92kB 2.8MB/s
Building wheels for collected packages: bitarray
  Building wheel for bitarray (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/1d/be/7b/08c830bb3e581399c1cb7263d9ce51950bb6a929d02229cd7d
Successfully built bitarray
Installing collected packages: bitarray
  Found existing installation: bitarray 0.9.3
    Uninstalling bitarray-0.9.3:
      Successfully uninstalled bitarray-0.9.3
Successfully installed bitarray-2.3.7
root@e6eab42d508c:/#
```

Installing the most recent version of setuptools causes a failed build.
```
$ docker run -it --rm conda
root@4674bdbd951d:/# /opt/conda/bin/pip install setuptools==60.9.3
Collecting setuptools==60.9.3
  Downloading https://files.pythonhosted.org/packages/3b/02/8d4d27b1cacaac2d129a27d17a22d92a2a5eedcb7817d4ed8ab0d4daf5c4/setuptools-60.9.3-py3-none-any.whl (1.1MB)
     |████████████████████████████████| 1.1MB 3.9MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 41.0.1
    Uninstalling setuptools-41.0.1:
      Successfully uninstalled setuptools-41.0.1
Successfully installed setuptools-60.9.3
root@4674bdbd951d:/# /opt/conda/bin/pip install bitarray==2.3.7
Collecting bitarray==2.3.7
  Downloading https://files.pythonhosted.org/packages/10/e6/cae15318a3074e38492b49989636802e3082dd1af4086259d54d9a382729/bitarray-2.3.7.tar.gz (89kB)
     |████████████████████████████████| 92kB 3.2MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 33, in <module>
        from ._importlib import metadata
      File "/opt/conda/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
        disable_importlib_metadata_finder(metadata)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
        import importlib_metadata
      File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 466, in <module>
        __version__ = version(__name__)
      File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 433, in version
        return distribution(package).version
      File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 406, in distribution
        return Distribution.from_name(package)
      File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 175, in from_name
        dists = resolver(name)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
        found = self._search_paths(context.name, context.path)
    AttributeError: 'str' object has no attribute 'name'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2ip3v_uk/bitarray/
root@4674bdbd951d:/#
```

Using setuptools 60.8.2 allows for a successful installation.
```
root@cb8c92bbe78f:/# /opt/conda/bin/pip install setuptools==60.8.2
Collecting setuptools==60.8.2
  Downloading https://files.pythonhosted.org/packages/ad/65/7b98718c0ecebbdae5a5251fffc43dd3800ff3d1a6f7cc1aa09cfbcf17a5/setuptools-60.8.2-py3-none-any.whl (1.1MB)
     |████████████████████████████████| 1.1MB 3.8MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 60.9.1
    Uninstalling setuptools-60.9.1:
      Successfully uninstalled setuptools-60.9.1
Successfully installed setuptools-60.8.2
root@cb8c92bbe78f:/# /opt/conda/bin/pip install bitarray==2.3.7
Collecting bitarray==2.3.7
  Downloading https://files.pythonhosted.org/packages/10/e6/cae15318a3074e38492b49989636802e3082dd1af4086259d54d9a382729/bitarray-2.3.7.tar.gz (89kB)
     |████████████████████████████████| 92kB 3.7MB/s
Building wheels for collected packages: bitarray
  Building wheel for bitarray (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/1d/be/7b/08c830bb3e581399c1cb7263d9ce51950bb6a929d02229cd7d
Successfully built bitarray
Installing collected packages: bitarray
  Found existing installation: bitarray 0.9.3
    Uninstalling bitarray-0.9.3:
      Successfully uninstalled bitarray-0.9.3
Successfully installed bitarray-2.3.7
```
