### ISSUE TITLE
Unable to install bitarray 0.8.2

### ISSUE THREAD

**Issue by akale2408** [ilanschnell/bitarray#57]
I get an error when I attempt to install this package.

```
$ pip install bitarray==0.8.2
Collecting bitarray==0.8.2
  Downloading [internal mirror]/bitarray-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b2/n_p6v7k57xzbxywzk1kykrnh0000gn/T/pip-build-s3sqrmv4/bitarray/setup.py", line 7, in <module>
        kwds['long_description'] = open('README.rst').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b2/n_p6v7k57xzbxywzk1kykrnh0000gn/T/pip-build-s3sqrmv4/bitarray/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

There is no error if I install `0.8.1`.

@ilanschnell

**Comment by earonesty** [comment]
Yeah, we're pegging 0.8.1 for now.    I feel like something changed in distutils.core and it's (ab)use of the current working directory.  bitarray, because of an unconventional use of the README, is more the victim here.

**Comment by ilanschnell** [comment]
I just put an exception around reading the `README.rst` file in `setup.py` and uploaded a new tarball to pypi.  Should work now.

**Comment by akale2408** [comment]
Works, thanks for the quick response 👍
